/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ravc.simpleimport.views;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.intellijthemes.FlatOneDarkIJTheme;
import static com.ravc.simpleimport.SimpleImport.SIProp;
import com.ravc.simpleimport.utils.FileTypeFilter;
import com.ravc.simpleimport.utils.SIConst;
import com.ravc.simpleimport.utils.TextAreaAppender;
import java.awt.Window;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.DefaultCaret;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

/**
 *
 * @author Rodrigo
 */
public class Main extends javax.swing.JFrame {

    final static Logger logger = Logger.getLogger("");

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        logger.setLevel(Level.INFO);

        DefaultCaret caret = (DefaultCaret) jtaLogs.getCaret(); // ←
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        TextAreaAppender appender = new TextAreaAppender(jtaLogs);
        Logger.getRootLogger().addAppender(appender);

        setIconImage(SIConst.ICON_SYSTEM);

        jtfClientesNome.setVisible(false);
        jtfClientesFantasia.setVisible(false);
        jtfClientesTelefone.setVisible(false);
        jtfClientesCidade.setVisible(false);
        jtfClientesBairro.setVisible(false);
        jtfClientesCPFCNPJ.setVisible(false);
        jtfClientesIEIM.setVisible(false);
        jtfClientesEndereco.setVisible(false);
        jtfClientesNumero.setVisible(false);
        jtfClientesComplemento.setVisible(false);
        jtfClientesCelular.setVisible(false);
        jtfClientesDtNasc.setVisible(false);
        jtfClientesContato.setVisible(false);
        jtfClientesEmail.setVisible(false);
        jtfClientesCEP.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jpLog = new javax.swing.JPanel();
        jpbProgress = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaLogs = new javax.swing.JTextArea();
        jpFields = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfPathClientsFile = new javax.swing.JTextField();
        jbSearchFileClients = new javax.swing.JButton();
        jbImportClients = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jtfClientesIEIM = new javax.swing.JTextField();
        jtfClientesCPFCNPJ = new javax.swing.JTextField();
        jtfClientesCelular = new javax.swing.JTextField();
        jtfClientesContato = new javax.swing.JTextField();
        jtfClientesDtNasc = new javax.swing.JTextField();
        jcbClientesDtNasc = new javax.swing.JCheckBox();
        jcbClientesEmail = new javax.swing.JCheckBox();
        jtfClientesEmail = new javax.swing.JTextField();
        jtfClientesFantasia = new javax.swing.JTextField();
        jcbClientesCPFCNPJ = new javax.swing.JCheckBox();
        jcbClientesFantasia = new javax.swing.JCheckBox();
        jcbClientesIEIM = new javax.swing.JCheckBox();
        jcbClientesCelular = new javax.swing.JCheckBox();
        jcbClientesTelefone = new javax.swing.JCheckBox();
        jtfClientesTelefone = new javax.swing.JTextField();
        jcbClientesNome = new javax.swing.JCheckBox();
        jtfClientesNome = new javax.swing.JTextField();
        jcbClientesContato = new javax.swing.JCheckBox();
        jtfClientesEndereco = new javax.swing.JTextField();
        jtfClientesNumero = new javax.swing.JTextField();
        jcbClientesBairro = new javax.swing.JCheckBox();
        jtfClientesBairro = new javax.swing.JTextField();
        jcbClientesCidade = new javax.swing.JCheckBox();
        jtfClientesCidade = new javax.swing.JTextField();
        jcbClientesCEP = new javax.swing.JCheckBox();
        jtfClientesCEP = new javax.swing.JTextField();
        jcbClientesComplemento = new javax.swing.JCheckBox();
        jcbClientesEndereco = new javax.swing.JCheckBox();
        jtfClientesComplemento = new javax.swing.JTextField();
        jcbClientesNumero = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfPathProductsFile = new javax.swing.JTextField();
        jbSeachFileProducts = new javax.swing.JButton();
        jbImportProducts = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jrbmDark = new javax.swing.JRadioButtonMenuItem();
        jrbmLight = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Import");
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1124, 486));
        setPreferredSize(new java.awt.Dimension(1124, 486));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 1, 1));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jpLog.setLayout(new java.awt.BorderLayout());

        jpbProgress.setPreferredSize(new java.awt.Dimension(146, 15));
        jpbProgress.setString("");
        jpbProgress.setStringPainted(true);
        jpLog.add(jpbProgress, java.awt.BorderLayout.SOUTH);

        jScrollPane2.setBorder(null);

        jtaLogs.setEditable(false);
        jtaLogs.setColumns(20);
        jtaLogs.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jtaLogs.setRows(5);
        jtaLogs.setFocusable(false);
        jtaLogs.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jtaLogs);

        jpLog.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpLog, java.awt.BorderLayout.CENTER);

        jpFields.setPreferredSize(new java.awt.Dimension(580, 389));
        jpFields.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Caminho do arquivo (csv/xlsx):");

        jbSearchFileClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_20px.png"))); // NOI18N
        jbSearchFileClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSearchFileClients.setMaximumSize(new java.awt.Dimension(45, 30));
        jbSearchFileClients.setMinimumSize(new java.awt.Dimension(45, 30));
        jbSearchFileClients.setPreferredSize(new java.awt.Dimension(45, 30));
        jbSearchFileClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchFileClientsActionPerformed(evt);
            }
        });

        jbImportClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_ssd_20px.png"))); // NOI18N
        jbImportClients.setText("Importar");
        jbImportClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbImportClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImportClientsActionPerformed(evt);
            }
        });

        jPanel4.setLayout(null);

        jtfClientesIEIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesIEIMKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesIEIM);
        jtfClientesIEIM.setBounds(300, 30, 40, 23);

        jtfClientesCPFCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesCPFCNPJKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesCPFCNPJ);
        jtfClientesCPFCNPJ.setBounds(120, 30, 40, 23);

        jtfClientesCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesCelularKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesCelular);
        jtfClientesCelular.setBounds(480, 60, 40, 23);

        jtfClientesContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesContatoKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesContato);
        jtfClientesContato.setBounds(480, 0, 40, 23);

        jtfClientesDtNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesDtNascKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesDtNasc);
        jtfClientesDtNasc.setBounds(120, 60, 40, 23);

        jcbClientesDtNasc.setText("Data Nasc");
        jcbClientesDtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesDtNascActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesDtNasc);
        jcbClientesDtNasc.setBounds(10, 60, 100, 23);

        jcbClientesEmail.setText("E-mail");
        jcbClientesEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesEmailActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesEmail);
        jcbClientesEmail.setBounds(190, 60, 103, 23);

        jtfClientesEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesEmailKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesEmail);
        jtfClientesEmail.setBounds(300, 60, 40, 23);

        jtfClientesFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesFantasiaKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesFantasia);
        jtfClientesFantasia.setBounds(300, 0, 40, 23);

        jcbClientesCPFCNPJ.setText("CPF/CNPJ");
        jcbClientesCPFCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesCPFCNPJActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesCPFCNPJ);
        jcbClientesCPFCNPJ.setBounds(10, 30, 110, 23);

        jcbClientesFantasia.setText("Fantasia");
        jcbClientesFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesFantasiaActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesFantasia);
        jcbClientesFantasia.setBounds(190, 0, 100, 23);

        jcbClientesIEIM.setText("Insc Est/Mun");
        jcbClientesIEIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesIEIMActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesIEIM);
        jcbClientesIEIM.setBounds(190, 30, 100, 23);

        jcbClientesCelular.setText("Telefone 2");
        jcbClientesCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesCelularActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesCelular);
        jcbClientesCelular.setBounds(370, 60, 100, 23);

        jcbClientesTelefone.setText("Telefone 1");
        jcbClientesTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesTelefoneActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesTelefone);
        jcbClientesTelefone.setBounds(370, 30, 100, 23);

        jtfClientesTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesTelefoneKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesTelefone);
        jtfClientesTelefone.setBounds(480, 30, 40, 23);

        jcbClientesNome.setText("Nome");
        jcbClientesNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesNomeActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesNome);
        jcbClientesNome.setBounds(10, 0, 100, 23);

        jtfClientesNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesNomeKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesNome);
        jtfClientesNome.setBounds(120, 0, 40, 23);

        jcbClientesContato.setText("Contato");
        jcbClientesContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesContatoActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesContato);
        jcbClientesContato.setBounds(370, 0, 100, 23);

        jtfClientesEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesEnderecoKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesEndereco);
        jtfClientesEndereco.setBounds(120, 100, 40, 23);

        jtfClientesNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesNumeroKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesNumero);
        jtfClientesNumero.setBounds(300, 100, 40, 23);

        jcbClientesBairro.setText("Bairro");
        jcbClientesBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesBairroActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesBairro);
        jcbClientesBairro.setBounds(370, 100, 100, 23);

        jtfClientesBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfClientesBairroActionPerformed(evt);
            }
        });
        jtfClientesBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesBairroKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesBairro);
        jtfClientesBairro.setBounds(480, 100, 40, 22);

        jcbClientesCidade.setText("Cidade");
        jcbClientesCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesCidadeActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesCidade);
        jcbClientesCidade.setBounds(370, 130, 103, 23);

        jtfClientesCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesCidadeKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesCidade);
        jtfClientesCidade.setBounds(480, 130, 40, 23);

        jcbClientesCEP.setText("CEP");
        jcbClientesCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesCEPActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesCEP);
        jcbClientesCEP.setBounds(190, 130, 103, 23);

        jtfClientesCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesCEPKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesCEP);
        jtfClientesCEP.setBounds(300, 130, 40, 23);

        jcbClientesComplemento.setText("Complemento");
        jcbClientesComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesComplementoActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesComplemento);
        jcbClientesComplemento.setBounds(10, 130, 100, 23);

        jcbClientesEndereco.setText("Endereço");
        jcbClientesEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesEnderecoActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesEndereco);
        jcbClientesEndereco.setBounds(10, 100, 90, 23);

        jtfClientesComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClientesComplementoKeyTyped(evt);
            }
        });
        jPanel4.add(jtfClientesComplemento);
        jtfClientesComplemento.setBounds(120, 130, 40, 23);

        jcbClientesNumero.setText("Numero");
        jcbClientesNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesNumeroActionPerformed(evt);
            }
        });
        jPanel4.add(jcbClientesNumero);
        jcbClientesNumero.setBounds(190, 100, 100, 23);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbImportClients))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfPathClientsFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSearchFileClients, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 406, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPathClientsFile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSearchFileClients, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jbImportClients)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jLabel2.setText("Caminho do arquivo (csv/xlsx):");

        jbSeachFileProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_20px.png"))); // NOI18N
        jbSeachFileProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSeachFileProducts.setMaximumSize(new java.awt.Dimension(45, 30));
        jbSeachFileProducts.setMinimumSize(new java.awt.Dimension(45, 30));
        jbSeachFileProducts.setPreferredSize(new java.awt.Dimension(45, 30));
        jbSeachFileProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeachFileProductsActionPerformed(evt);
            }
        });

        jbImportProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_ssd_20px.png"))); // NOI18N
        jbImportProducts.setText("Importar");
        jbImportProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImportProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 406, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbImportProducts))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfPathProductsFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSeachFileProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPathProductsFile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSeachFileProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(jbImportProducts)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produtos", jPanel3);

        jpFields.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jpFields, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Arquivo");

        jMenu3.setText("Tema");

        buttonGroup1.add(jrbmDark);
        jrbmDark.setSelected(true);
        jrbmDark.setText("Escuro");
        jrbmDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmDarkActionPerformed(evt);
            }
        });
        jMenu3.add(jrbmDark);

        buttonGroup1.add(jrbmLight);
        jrbmLight.setText("Claro");
        jrbmLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmLightActionPerformed(evt);
            }
        });
        jMenu3.add(jrbmLight);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        jMenu4.setText("Manuais");

        jMenuItem2.setText("Importação");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Layout de arquivos");
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSearchFileClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchFileClientsActionPerformed
        getFileImport(jtfPathClientsFile);
    }//GEN-LAST:event_jbSearchFileClientsActionPerformed

    private void jbSeachFileProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeachFileProductsActionPerformed
        getFileImport(jtfPathProductsFile);
    }//GEN-LAST:event_jbSeachFileProductsActionPerformed

    private void jbImportProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImportProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbImportProductsActionPerformed

    private void jbImportClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImportClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbImportClientsActionPerformed

    private void jtfClientesEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesEnderecoKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesEnderecoKeyTyped

    private void jtfClientesNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesNumeroKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesNumeroKeyTyped

    private void jtfClientesIEIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesIEIMKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesIEIMKeyTyped

    private void jtfClientesCPFCNPJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesCPFCNPJKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesCPFCNPJKeyTyped

    private void jtfClientesCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesCelularKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesCelularKeyTyped

    private void jcbClientesCPFCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesCPFCNPJActionPerformed
        if (jcbClientesCPFCNPJ.isSelected()) {
            jtfClientesCPFCNPJ.setVisible(true);
        } else {
            jtfClientesCPFCNPJ.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesCPFCNPJActionPerformed

    private void jcbClientesIEIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesIEIMActionPerformed
        if (jcbClientesIEIM.isSelected()) {
            jtfClientesIEIM.setVisible(true);
        } else {
            jtfClientesIEIM.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesIEIMActionPerformed

    private void jcbClientesEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesEnderecoActionPerformed
        if (jcbClientesEndereco.isSelected()) {
            jtfClientesEndereco.setVisible(true);
        } else {
            jtfClientesEndereco.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesEnderecoActionPerformed

    private void jcbClientesNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesNumeroActionPerformed
        if (jcbClientesNumero.isSelected()) {
            jtfClientesNumero.setVisible(true);
        } else {
            jtfClientesNumero.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesNumeroActionPerformed

    private void jcbClientesCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesCelularActionPerformed
        if (jcbClientesCelular.isSelected()) {
            jtfClientesCelular.setVisible(true);
        } else {
            jtfClientesCelular.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesCelularActionPerformed

    private void jcbClientesTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesTelefoneActionPerformed
        if (jcbClientesTelefone.isSelected()) {
            jtfClientesTelefone.setVisible(true);
        } else {
            jtfClientesTelefone.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesTelefoneActionPerformed

    private void jtfClientesTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesTelefoneKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesTelefoneKeyTyped

    private void jcbClientesNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesNomeActionPerformed
        if (jcbClientesNome.isSelected()) {
            jtfClientesNome.setVisible(true);
        } else {
            jtfClientesNome.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesNomeActionPerformed

    private void jtfClientesNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesNomeKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesNomeKeyTyped

    private void jcbClientesContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesContatoActionPerformed
        if (jcbClientesContato.isSelected()) {
            jtfClientesContato.setVisible(true);
        } else {
            jtfClientesContato.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesContatoActionPerformed

    private void jtfClientesContatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesContatoKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesContatoKeyTyped

    private void jcbClientesBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesBairroActionPerformed
        if (jcbClientesBairro.isSelected()) {
            jtfClientesBairro.setVisible(true);
        } else {
            jtfClientesBairro.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesBairroActionPerformed

    private void jtfClientesBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfClientesBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClientesBairroActionPerformed

    private void jtfClientesBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesBairroKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesBairroKeyTyped

    private void jcbClientesCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesCidadeActionPerformed
        if (jcbClientesCidade.isSelected()) {
            jtfClientesCidade.setVisible(true);
        } else {
            jtfClientesCidade.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesCidadeActionPerformed

    private void jtfClientesCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesCidadeKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesCidadeKeyTyped

    private void jtfClientesDtNascKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesDtNascKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesDtNascKeyTyped

    private void jcbClientesDtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesDtNascActionPerformed
        if (jcbClientesDtNasc.isSelected()) {
            jtfClientesDtNasc.setVisible(true);
        } else {
            jtfClientesDtNasc.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesDtNascActionPerformed

    private void jcbClientesCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesCEPActionPerformed
        if (jcbClientesCEP.isSelected()) {
            jtfClientesCEP.setVisible(true);
        } else {
            jtfClientesCEP.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesCEPActionPerformed

    private void jtfClientesCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesCEPKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesCEPKeyTyped

    private void jcbClientesEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesEmailActionPerformed
        if (jcbClientesEmail.isSelected()) {
            jtfClientesEmail.setVisible(true);
        } else {
            jtfClientesEmail.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesEmailActionPerformed

    private void jtfClientesEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesEmailKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfClientesEmailKeyTyped

    private void jtfClientesFantasiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesFantasiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClientesFantasiaKeyTyped

    private void jcbClientesFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesFantasiaActionPerformed
        if (jcbClientesFantasia.isSelected()) {
            jtfClientesFantasia.setVisible(true);
        } else {
            jtfClientesFantasia.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesFantasiaActionPerformed

    private void jcbClientesComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesComplementoActionPerformed
        if (jcbClientesComplemento.isSelected()) {
            jtfClientesComplemento.setVisible(true);
        } else {
            jtfClientesComplemento.setVisible(false);
        }
    }//GEN-LAST:event_jcbClientesComplementoActionPerformed

    private void jtfClientesComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClientesComplementoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClientesComplementoKeyTyped

    private void jrbmLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmLightActionPerformed
        changeTheme("Light");
    }//GEN-LAST:event_jrbmLightActionPerformed

    private void jrbmDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmDarkActionPerformed
        changeTheme("Dark");
    }//GEN-LAST:event_jrbmDarkActionPerformed

    private  void changeTheme(String theme) {
        if (theme.equals("Dark")) {
            SIProp.setProp("tema", "Dark");
            FlatOneDarkIJTheme.install();
        } else if (theme.equals("Light")) {
            SIProp.setProp("tema", "Light");
            FlatIntelliJLaf.install();
        }
        
        for (Window window : Window.getWindows()) {
            SwingUtilities.updateComponentTreeUI(window);
        }
    }

    public void getFileImport(JTextField jtf) {
        JFileChooser fileChooser = new JFileChooser(".");
        FileFilter txtFilter = new FileTypeFilter(".xlsx", "Excel Padrão");
        FileFilter csvFilter = new FileTypeFilter(".csv", "Excel separado por ponto e virgula");
        fileChooser.addChoosableFileFilter(txtFilter);
        fileChooser.addChoosableFileFilter(csvFilter);
        fileChooser.setFileFilter(csvFilter);
        int status = fileChooser.showOpenDialog(null);
        if (status == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            jtf.setText(selectedFile.getPath());
            logger.info("Selecionado arquivo:");
            logger.info(selectedFile.getPath());
            logger.info("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbImportClients;
    private javax.swing.JButton jbImportProducts;
    private javax.swing.JButton jbSeachFileProducts;
    private javax.swing.JButton jbSearchFileClients;
    private javax.swing.JCheckBox jcbClientesBairro;
    private javax.swing.JCheckBox jcbClientesCEP;
    private javax.swing.JCheckBox jcbClientesCPFCNPJ;
    private javax.swing.JCheckBox jcbClientesCelular;
    private javax.swing.JCheckBox jcbClientesCidade;
    private javax.swing.JCheckBox jcbClientesComplemento;
    private javax.swing.JCheckBox jcbClientesContato;
    private javax.swing.JCheckBox jcbClientesDtNasc;
    private javax.swing.JCheckBox jcbClientesEmail;
    private javax.swing.JCheckBox jcbClientesEndereco;
    private javax.swing.JCheckBox jcbClientesFantasia;
    private javax.swing.JCheckBox jcbClientesIEIM;
    private javax.swing.JCheckBox jcbClientesNome;
    private javax.swing.JCheckBox jcbClientesNumero;
    private javax.swing.JCheckBox jcbClientesTelefone;
    private javax.swing.JPanel jpFields;
    private javax.swing.JPanel jpLog;
    private javax.swing.JProgressBar jpbProgress;
    private javax.swing.JRadioButtonMenuItem jrbmDark;
    private javax.swing.JRadioButtonMenuItem jrbmLight;
    private javax.swing.JTextArea jtaLogs;
    private javax.swing.JTextField jtfClientesBairro;
    private javax.swing.JTextField jtfClientesCEP;
    private javax.swing.JTextField jtfClientesCPFCNPJ;
    private javax.swing.JTextField jtfClientesCelular;
    private javax.swing.JTextField jtfClientesCidade;
    private javax.swing.JTextField jtfClientesComplemento;
    private javax.swing.JTextField jtfClientesContato;
    private javax.swing.JTextField jtfClientesDtNasc;
    private javax.swing.JTextField jtfClientesEmail;
    private javax.swing.JTextField jtfClientesEndereco;
    private javax.swing.JTextField jtfClientesFantasia;
    private javax.swing.JTextField jtfClientesIEIM;
    private javax.swing.JTextField jtfClientesNome;
    private javax.swing.JTextField jtfClientesNumero;
    private javax.swing.JTextField jtfClientesTelefone;
    private javax.swing.JTextField jtfPathClientsFile;
    private javax.swing.JTextField jtfPathProductsFile;
    // End of variables declaration//GEN-END:variables
}
