# This is a basic workflow to help you get started with Actions

name: Java CI

# Controls when the workflow will run
on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      
        with:
          java-version: '8'
          
      # Runs a single command using the runners shell
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
