name: Maven Compiler

on:
  push:
    branches: [ master ]

jobs:

  compile:
    runs-on: windows-2022
    name: Compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Compile code
      run: mvn -B compile && dir
      
  package:
    runs-on: windows-2022
    needs: [ compile ]
    name: Empacotar executavel
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - run: mvn -B package --file pom.xml
    - run: mkdir simpleimport && cp target/*.exe simpleimport
    - uses: actions/upload-artifact@v2
      with:
        name: SimpleImport
        path: simpleimport
        
  libs:
    runs-on: windows-2022
    needs: [ compile ]
    name: Salvar libs utilizadas
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - run: mvn install dependency:copy-dependencies 
    - run: mkdir lib && cp target/dependency/*.jar lib
    - uses: actions/upload-artifact@v2
      with:
        name: lib
        path: lib

  ftp-deploy:
    runs-on: windows-2022
    needs: [ package, libs ]
    name: Atualizar FTP
    steps:
    - uses: actions/checkout@v2
    - name: Enviando libs
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.evoluti.info
        username: u775355011.simpleimport
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./target/dependency/
        server-dir: ./teste/
    - name: Enviando executavel
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.evoluti.info
        username: u775355011.simpleimport
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./target/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/target/dependency/**
          **/target/.jar*/**
