name: Maven Compiler

on:
  push:
    branches: [ master ]

jobs:

  compile:
    runs-on: windows-2022
    name: Compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Compile code
      run: mvn -B compile && dir
      
  package:
    runs-on: windows-2022
    needs: [ compile ]
    name: Empacotar executavel
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/*.exe staging
    - uses: actions/upload-artifact@v2
      with:
        name: SimpleImport
        path: staging
        
  libs:
    runs-on: windows-2022
    needs: [ compile ]
    name: Salvar libs utilizadas
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - run: mvn -B package --file pom.xml
    - run: mkdir libs && cp target/lib/*.jar libs
    - uses: actions/upload-artifact@v2
      with:
        name: lib
        path: libs
