name: Notificar

on:
  workflow_run:
    workflows: [Maven Compiler]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Notificação Sucesso
    steps:
    - uses: actions/checkout@v2
    - name: Enviar E-mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ github.job }} job de ${{ github.repository }} teve ${{ job.status }}
        body: ${{ github.job }} job no worflow ${{ github.workflow }} do ${{ github.repository }} teve ${{ job.status }}
        to: rodrigoaguiar35@gmail.com
        from: Github
  on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    name: Notificação Falha
    steps:
    - uses: actions/checkout@v2
    - name: Enviar E-mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ github.job }} job de ${{ github.repository }} teve ${{ job.status }}
        body: ${{ github.job }} job no worflow ${{ github.workflow }} do ${{ github.repository }} teve ${{ job.status }}
        to: rodrigoaguiar35@gmail.com
        from: Github