name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  compile:
    name: Compilando código
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Compile code
      run: mvn -B compile

  package:
    name: Empacotar para executável
    runs-on: windows-2022
    needs: [ compile ]
    steps:
    - uses: actions/checkout@v2
    - name: Subindo JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Gerando executável
      run: mvn -B package --file pom.xml && mkdir staging && cp target/*.exe staging
    - name: Subindo executável
      uses: actions/upload-artifact@v2
      with:
        name: SimpleImport
        path: staging/SimpleImport.exe

  release:
      name: Liberar versão
      runs-on: windows-2022
      needs: [ package ]
      steps:
        - uses: actions/checkout@v2
        - name: Baixando executável
        - uses: actions/download-artifact@master
          with:
            name: SimpleImport
            path: staging/SimpleImport.exe
        - name: Gerando versão
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: target/SimpleImport.exe
            asset_name: SimpleImport
            tag: ${{ github.ref }}
            overwrite: true
            body: "Release compiled to EXE file"
