name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  compile:
    runs-on: windows-2022
    name: Compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Compile code
      run: mvn -B compile

  build:
    name: Publish binaries
    runs-on: windows-2022
    needs: [ compile ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Compile code
      run: mvn -B package --file pom.xml
      run: mkdir staging && cp target/*.exe staging
      uses: actions/upload-artifact@v2
      with:
        name: SimpleImport
        path: staging/SimpleImport.exe
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/SimpleImport.exe
        asset_name: SimpleImport
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release compiled to EXE file"
